# Generated by Django 4.2.10 on 2024-03-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_one',
            new_name='updated_on',
        ),
    ]
